name: Selenium Web Testing

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t selenium-web-testing .

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app selenium-web-testing

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/test_report.html
